title: American Shavian Transliterator
description: "Transliterates English written in the Latin alphabet to the Shavian alphabet, exactly as it is pronounced in the \"general\" American dialect."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
nav:
  - text: "FAQ"
    href: "faq"